WelfareSurveySystem.WebUI/Controllers/EmployeesManage/EmployeesPersonalDetailsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WelfareSurveySystem.Data;
using WelfareSurveySystem.Domain.Business;
using WelfareSurveySystem.Domain.Entities;

namespace WelfareSurveySystem.WebUI.Controllers.EmployeesManage
{
    //[Authorize(Roles = "resercher")]

    public class EmployeesPersonalDetailsController : Controller
    {

        private IWelfareSurveySystemBusiness employeesManage;

        public WelfareSurveySystemDBContext Db { get; }

        public EmployeesPersonalDetailsController(IWelfareSurveySystemBusiness employeesManage, WelfareSurveySystemDBContext db)
        {
            this.employeesManage = employeesManage;
            Db = db;
        }

        public IActionResult List()
        {
            var empList = employeesManage.GetAllEmployees();
            return View(empList);
        }

        public IActionResult Index(string serviceNo = null)
        {
            Employee emp = null;
            //string message = "Employee not found...";
            if (serviceNo != null)
            {
                //TODO: add GetEmployeeByServiceNo() in Data and Domain Layer
                emp = employeesManage.GetAllEmployees().Where(e => e.ServiceNo.Trim() == serviceNo.Trim()).FirstOrDefault();
                //message = "";
                if (emp == null)
                {
                    TempData["Msg"] = "Employee not found, search again";
                }
            }



            return View(emp);
        }


        // www.sdfsdfsdfsdf.com/EmployeesPersonalDetails/Create
        //EmployeesPersonalDetails

        [HttpGet]
        public IActionResult CreatePersonalDetails()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreatePersonalDetails(Employee employee)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            employee.SysDate = DateTime.Now;
            employeesManage.SaveEmployee(employee);
            TempData["SuccessMsg"] = $"Employee {employee.FullName} personal details created successfully";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult AddParents(int empID)
        {
            //ViewBag.Employee = employee;
            //var emp = employeesManage.GetEmployee(id);

            ViewBag.EmployeeID = empID;  //to take same employeeID from create new employee view

            //We have to add in repository to get all parents based on employee ID List<Parent> GetParents(int empID);
            List<Parent> parents = Db.Parents.Where(p =>p.EmployeeID == empID).ToList();
            return View(parents);
        }


        [HttpPost]
        public IActionResult AddParents(Parent parent)
        {
            Employee associatedEmployee = employeesManage.GetEmployee(parent.EmployeeID);

            if (!ModelState.IsValid || associatedEmployee == null)
            {
                TempData["ErrorMsg"] = "Error submitting the form.";
                List<Parent> existingParents = employeesManage.GetAllParents();
                return View(existingParents);
            }

            // At this point, the form submission is valid and the associated data exists
            //parent.EmployeeID = empID; // Set the EmployeeID for the Parent

            employeesManage.SaveParent(parent.EmployeeID, parent); // Save parent data to the database

            ViewBag.Msg = parent.Name;

            return View("Index");
        }

        ///////////////////////////////
        [HttpGet]
        public IActionResult AddChildren(int empID)
        {
            //ViewBag.Employee = employee;
            //var emp = employeesManage.GetEmployee(id);

            ViewBag.EmployeeID = empID;  //to take same employeeID from create new employee view
            List<Children> children = employeesManage.GetChildren(empID); // this method

            return View(children);
        }


        [HttpPost]
        public IActionResult AddChildren(Children children)
        {
            Employee associatedEmployee = employeesManage.GetEmployee(children.EmployeeID);

            if (!ModelState.IsValid || associatedEmployee == null)
            {
                TempData["ErrorMsg"] = "Error submitting the form.";
                List<Children> existingChildren = employeesManage.GetChildren(children.EmployeeID);
                return View(existingChildren);
            }

            // At this point, the form submission is valid and the associated data exists
            //parent.EmployeeID = empID; // Set the EmployeeID for the Parent

            employeesManage.SaveChildren(children.EmployeeID, children); // Save parent data to the database

            ViewBag.Msg = children.Name;

            return View("Index");
        }
        //ssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
        [HttpGet]
        public IActionResult AddSpouse(int empID)
        {
            //ViewBag.Employee = employee;
            //var emp = employeesManage.GetEmployee(id);

            ViewBag.EmployeeID = empID;  //to take same employeeID from create new employee view
            List<Spouse> spouse = employeesManage.GetSpouse(empID); // this method

            return View(spouse);
        }


        [HttpPost]
        public IActionResult AddSpouse(Spouse spouse)
        {
            Employee associatedEmployee = employeesManage.GetEmployee(spouse.EmployeeID);

            if (!ModelState.IsValid || associatedEmployee == null)
            {
                TempData["ErrorMsg"] = "Error submitting the form.";
                List<Spouse> existingSpouse = employeesManage.GetSpouse(spouse.EmployeeID);
                return View(existingSpouse);
            }

            // At this point, the form submission is valid and the associated data exists
            //parent.EmployeeID = empID; // Set the EmployeeID for the Parent

            employeesManage.SaveSpouse(spouse.EmployeeID, spouse); // Save parent data to the database

            ViewBag.Msg = spouse.Name;

            return View("Index");
        }
        //siblingggggggggggggggggggggggggg
        [HttpGet]
        public IActionResult AddSibling(int empID)
        {
            //ViewBag.Employee = employee;
            //var emp = employeesManage.GetEmployee(id);

            ViewBag.EmployeeID = empID;  //to take same employeeID from create new employee view
            List<Sibling> sibling = employeesManage.GetSibling(empID); // this method

            return View(sibling);
        }


        [HttpPost]
        public IActionResult AddSibling(Sibling sibling)
        {
            Employee associatedEmployee = employeesManage.GetEmployee(sibling.EmployeeID);

            if (!ModelState.IsValid || associatedEmployee == null)
            {
                TempData["ErrorMsg"] = "Error submitting the form.";
                List<Spouse> existingSpouse = employeesManage.GetSpouse(sibling.EmployeeID);
                return View(existingSpouse);
            }

            // At this point, the form submission is valid and the associated data exists
            //parent.EmployeeID = empID; // Set the EmployeeID for the Parent

            employeesManage.SaveSibling(sibling.EmployeeID, sibling); // Save parent data to the database

            ViewBag.Msg = sibling.Name;

            return View("Index");
        }

        [HttpGet]
        public IActionResult AddRealEstate(int empID)
        {
            ViewBag.EmployeeID = empID;  //to take same employeeID from create new employee view
            List<RealEstate> realEstates = employeesManage.GetAllRealEstate().Where(e => e.EmployeeID == empID).ToList(); // this method

            var realEstateTypes = employeesManage.GetRealEstateTypes(); // to fill dropdown

            // for dropdown values
            ViewBag.RealEstateTypes = from r in realEstateTypes
                                      select new SelectListItem { Text = r.RealEstateTypeName, Value = r.RealEstateTypeId.ToString() };


            return View(realEstates);
        }
        [HttpPost]
        public IActionResult AddRealEstate(RealEstate realEstate)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            employeesManage.SaveRealEstate(realEstate);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult RealEstateEdit(int id)
        {
            // return a filled view
            RealEstate realEstate = employeesManage.GetAllRealEstate().Where(r => r.RealEstateId == id).FirstOrDefault();
            var realEstateTypes = employeesManage.GetRealEstateTypes(); // to fill dropdown

            // for dropdown values
            ViewBag.RealEstateTypes = from r in realEstateTypes
                                      select new SelectListItem { Text = r.RealEstateTypeName, Value = r.RealEstateTypeId.ToString() };

            return View(realEstate);
        }

        [HttpPost]
        public IActionResult RealEstateEdit(RealEstate realEstate)
        {
            if (!ModelState.IsValid)
                return View();

            employeesManage.EditRealEstate(0, 0, realEstate);//change this method
            //return RedirectToAction("AddRealEstate", realEstate.EmployeeID);
            return View("Index");
        }

        [HttpGet]
        public IActionResult RealEstateDelete(int id)
        {
            employeesManage.DeleteRealEstate(0, id); // change
            return View("Index");
        }


        //parent edit form
        [HttpGet]
        public IActionResult EditParents(int id)
        {
          
            var parentToEdit = employeesManage.GetParent(id);
            
            return View(parentToEdit);
        }

        [HttpPost]
        public IActionResult EditParents(Parent Parentedit)

WelfareSurveySystem.WebUI/Views/EmployeesPersonalDetails/AddParents.cshtml
@model IEnumerable<WelfareSurveySystem.Domain.Entities.Parent>



@{
    ViewData["Title"] = "AddParents";
}

<h1>Add Parents</h1>

@if (Model.Count() >= 1)
{
    <table class="table" border="1">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.ParentId)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.EmployeeID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PersonId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdCard)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthDay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HealthStatues)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaritalStatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                    @Html.DisplayFor(modelItem => item.ParentId)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.EmployeeID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PersonId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdCard)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BirthDay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HealthStatues)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JobName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaritalStatus)
                </td>
               @* <td>
                        @Html.ActionLink("Edit", "EditParents", new {id=item.PersonId  }) |

                        @Html.ActionLink("Delete", "ConfirmDelete", new { id=item.PersonId})
                </td>*@
                    <td>
                        <a asp-action="ConfirmDelete"
                   asp-route-id="@item.PersonId"
                           class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>

                    </td>
                    <td>
                        <a asp-action="EditParents" asp-route-id="@item.PersonId" class="btn btn-primary">Edit</a>
                    </td>
            </tr>
        }
    </tbody>
</table>
}
@*@if (Model.Count() == null) {*@

  

    <div class="row">
        <div class="col-md-4">
            <form asp-action="AddParents">
                <input type="hidden" name="EmployeeID" value="@ViewBag.EmployeeID">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
               @* <div class="mb-3">
                    <label asp-for="@item.EmployeeID" class="control-label"></label>
                    <input asp-for="EmployeeID" class="form-control" />
                    <span asp-validation-for="EmployeeID" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <label  class="control-label">Name</label>
                    <input name="Name" class="form-control" />
                    @*<span asp-validation-for="Name" class="text-danger"></span>*@
                </div>
                <div class="form-group">
                    <label  class="control-label">ID Card</label>
                    <input name="IdCard" class="form-control" />
                    @*<span asp-validation-for="IdCard" class="text-danger"></span>*@
                </div>
                @*<div class="form-group">
                    <label  class="control-label">Birth Day</label>
                    <input name="BirthDay" class="form-control"/>
                </div>*@
            <div class="form-group">
                <label class="control-label">Birth Day</label>
                <input name="BirthDay" class="form-control" type="datetime-local" />
            </div>
           
                <div class="form-group">
                    <label  class="control-label">Health Statues</label>
                    <input name="HealthStatues" class="form-control" />
                    @*<span asp-validation-for="HealthStatues" class="text-danger"></span>*@
                </div>
                <div class="form-group">
                    <label class="control-label">Job Name</label>
                    <input name="JobName" class="form-control" />
                    @*<span asp-validation-for="JobName" class="text-danger"></span>*@
                </div>
                <div class="form-group">
                    <label  class="control-label">Marital Status</label>
                    <input name="MaritalStatus" class="form-control" />
                    @*<span asp-validation-for="MaritalStatus" class="text-danger"></span>*@
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

   
    
 

WelfareSurveySystem.WebUI/Views/EmployeesPersonalDetails/AddSibling.cshtml
@model IEnumerable<WelfareSurveySystem.Domain.Entities.Sibling>

@{
    ViewData["Title"] = "AddSibling";

}


<h1>Add Spouse</h1>

@if (Model.Count() >= 1)
{
    <table class="table">
        <thead>
            <tr>
                @*<th>
            @Html.DisplayNameFor(model => model.ParentId)
            </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.EmployeeID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PersonId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                @* <th>
            @Html.DisplayNameFor(model => model.IdCard)
            </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.BirthDay)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HealthStatues)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.JobName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MaritalStatus)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @*<td>
            @Html.DisplayFor(modelItem => item.ParentId)
            </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.EmployeeID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PersonId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    @* <td>
            @Html.DisplayFor(modelItem => item.IdCard)
            </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.BirthDay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HealthStatues)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JobName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaritalStatus)
                    </td>
                    <td>
                        @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                        <a href="@Url.Action("Delete", new { id = item.EmployeeID  })" onclick="return confirm('Are you sure you want to delete this item?');">
                            <span class="bi bi-trash"></span>
                        </a>*@

                    <td>
                        <a asp-action="ConfirmDeleteSibling"
                   asp-route-id="@item.PersonId"
                           class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>

                    </td>
                    <td>
                        <a asp-action="EditSibling" asp-route-id="@item.PersonId" class="btn btn-primary">Edit</a>
                    </td>

                    </td>
                </tr>
            }
        </tbody>
    </table>
}
@*@if (Model.Count() == null) {*@



<div class="row">
    <div class="col-md-4">
        <form asp-action="AddSibling">
            <input type="hidden" name="EmployeeID" value="@ViewBag.EmployeeID">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="mb-3">
            <label asp-for="@item.EmployeeID" class="control-label"></label>
            <input asp-for="EmployeeID" class="form-control" />
            <span asp-validation-for="EmployeeID" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label class="control-label">Name</label>
                <input name="Name" class="form-control" />
                @*<span asp-validation-for="Name" class="text-danger"></span>*@
            </div>
            @* <div class="form-group">
            <label class="control-label">ID Card</label>
            <input name="IdCard" class="form-control" />
            <span asp-validation-for="IdCard" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label class="control-label">Birth Day</label>
                <input name="BirthDay" class="form-control" type="datetime-local" />
                @*<span asp-validation-for="BirthDay" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label class="control-label">Health Statues</label>
                <input name="HealthStatues" class="form-control" />
                @*<span asp-validation-for="HealthStatues" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label class="control-label">Job Name</label>
                <input name="JobName" class="form-control" />
                @*<span asp-validation-for="JobName" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label class="control-label">Marital Status</label>
                <input name="MaritalStatus" class="form-control" />
                @*<span asp-validation-for="MaritalStatus" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

WelfareSurveySystem.WebUI/Views/EmployeesPersonalDetails/AddSpouse.cshtml
@model IEnumerable<WelfareSurveySystem.Domain.Entities.Spouse>

@{
    ViewData["Title"] = "AddSpouse";
   
}


<h1>Add Spouse</h1>

@if (Model.Count() >= 1)
{
    <table class="table">
        <thead>
            <tr>
                @*<th>
            @Html.DisplayNameFor(model => model.ParentId)
            </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.EmployeeID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PersonId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                @* <th>
            @Html.DisplayNameFor(model => model.IdCard)
            </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.BirthDay)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HealthStatues)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.JobName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MaritalStatus)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @*<td>
            @Html.DisplayFor(modelItem => item.ParentId)
            </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.EmployeeID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PersonId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    @* <td>
            @Html.DisplayFor(modelItem => item.IdCard)
            </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.BirthDay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HealthStatues)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JobName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaritalStatus)
                    </td>
                    <td>
                       @* @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                        <a href="@Url.Action("Delete", new { id = item.EmployeeID  })" onclick="return confirm('Are you sure you want to delete this item?');">
                            <span class="bi bi-trash"></span>
                        </a>*@

                    <td>
                        <a asp-action="ConfirmDeleteSpouse"
                   asp-route-id="@item.PersonId"
                           class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>

                    </td>
                    <td>
                        <a asp-action="EditSpouse" asp-route-id="@item.PersonId" class="btn btn-primary">Edit</a>
                    </td>


                    
                </tr>
            }
        </tbody>
    </table>
}
@*@if (Model.Count() == null) {*@



<div class="row">
    <div class="col-md-4">
        <form asp-action="AddSpouse">
            <input type="hidden" name="EmployeeID" value="@ViewBag.EmployeeID">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="mb-3">
            <label asp-for="@item.EmployeeID" class="control-label"></label>
            <input asp-for="EmployeeID" class="form-control" />
            <span asp-validation-for="EmployeeID" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label class="control-label">Name</label>
                <input name="Name" class="form-control" />
                @*<span asp-validation-for="Name" class="text-danger"></span>*@
            </div>
            @* <div class="form-group">
            <label class="control-label">ID Card</label>
            <input name="IdCard" class="form-control" />
            <span asp-validation-for="IdCard" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label class="control-label">Birth Day</label>
                <input name="BirthDay" class="form-control" type="datetime-local" />
                @*<span asp-validation-for="BirthDay" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label class="control-label">Health Statues</label>
                <input name="HealthStatues" class="form-control" />
                @*<span asp-validation-for="HealthStatues" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label class="control-label">Job Name</label>
                <input name="JobName" class="form-control" />
                @*<span asp-validation-for="JobName" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label class="control-label">Marital Status</label>
                <input name="MaritalStatus" class="form-control" />
                @*<span asp-validation-for="MaritalStatus" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

WelfareSurveySystem.WebUI/Views/EmployeesPersonalDetails/DeleteConParents.cshtml
@model WelfareSurveySystem.Domain.Entities.Parent


<h1>Confirm Delete</h1>
<hr>

<h3>Wish to delete @Model.Name ?</h3>

<a asp-action="ConfirmDelete" asp-controller="EmployeesPersonalDetails" asp-route-id="@Model.PersonId" class="btn btn-danger">Yes</a>
<a asp-action="Index" asp-controller="EmployeesPersonalDetails" class="btn btn-info">No</a>

@*<i class="bi bi-trash3"></i>*@

WelfareSurveySystem.WebUI/Views/EmployeesPersonalDetails/DeleteConSibling.cshtml
@model WelfareSurveySystem.Domain.Entities.Sibling


<h1>Confirm Delete</h1>
<hr>

<h3>Wish to delete @Model.Name ?</h3>

<a asp-action="ConfirmDelete" asp-controller="EmployeesPersonalDetails" asp-route-id="@Model.PersonId" class="btn btn-danger">Yes</a>
<a asp-action="Index" asp-controller="EmployeesPersonalDetails" class="btn btn-info">No</a>

@*<i class="bi bi-trash3"></i>*@

WelfareSurveySystem.WebUI/Views/EmployeesPersonalDetails/NewInlineEdit.cshtml
@model List<WelfareSurveySystem.Domain.Entities.Parent>
<h2>Manage PArent</h2>
<hr />


<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>@TempData["Msg"]</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

<table class="table table-bordered">
    <tr>
        <td>Name</td>
        <td>IdCard</td>
        <td>BirthDay</td>
        <td>HealthStatues</td>
        <td>JobName</td>
        <td>MaritalStatus</td>
        <td>Delete</td>
        <td>Edit</td>
    </tr>

    @foreach (var item in Model)
    {
        if (ViewBag.EmployeeID == item.PersonId)
        {
            <tr>
                <form action="EditParents" method="post">
                    <input type="hidden" name="PersonId" value="@item.PersonId" />
                <td><input type="text" class="form-control" name="Name" value="@item.Name" /></td>
                <td><input type="text" class="form-control" name="IdCard" value="@item.IdCard" /></td>
                <td><input type="text" class="form-control" name="BirthDay" value="@item.BirthDay" /></td>
                <td><input type="text" class="form-control" name="HealthStatues" value="@item.HealthStatues" /></td>
                <td><input type="text" class="form-control" name="JobName" value="@item.JobName"/></td>
                <td><input type="text" class="form-control" name="MaritalStatus" value="@item.MaritalStatus" /></td>
                <td>
                    <input type="submit" class="form-control btn btn-success" name="btnSubmit" value="Save" />
                </td>
                <td>
                    <a asp-action="Index" asp-controller="EmployeesPersonalDetails" class="btn btn-warning">Cancel</a>
                </td>
                </form>
            </tr>
        }
        else
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.IdCard</td>
                <td>@item.BirthDay</td>
                <td>@item.HealthStatues</td>
                <td>@item.JobName</td>
                <td>@item.MaritalStatus</td>
                <td>
                    <a asp-action="ConfirmDelete"
               asp-route-id="@item.PersonId"
                       class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>

                </td>
                <td>
                    <a asp-action="EditParents" asp-route-id="@item.PersonId" class="btn btn-primary">Edit</a>
                </td>
            </tr>
        }



    }
</table>